### ISSUE TITLE
Exception "IndexError: list index out of range" while running model.py

### ISSUE THREAD

**Issue by iabhi7** [sallamander/headline-generation#1]
While running model.py I am getting "IndexError: list index out of range". Here is the error snippet. 
I tried few hacks but nothing worked. Any idea to solve this?

    Traceback (most recent call last):
      File "model.py", line 481, in <module>
        embed_dim = sys.argv[1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "model.py", line 483, in <module>
        raise Exception("Usage: {} embed_dim".format(sys.argv[0]))
    Exception: Usage: model.py embed_dim

**Comment by sallamander** [comment]
Sorry this has taken so long, I must have not seen the notification. Can you please send the code that you're running this with? It looks like you're not passing in an expected command line parameter.
